# Generated by Django 3.2 on 2022-11-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221108_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='own_token',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='fb_token',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='google_token',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='twitter_token',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
