# Generated by Django 3.2 on 2022-11-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221108_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='dj', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='dj', max_length=255)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('Order confirmed', 'Order confirmed'), ('Processing Order', 'Processing Order'), ('Quality Check', 'Quality Check'), ('Dispatched Item', 'Dispatched Item'), ('Product Deliverd', 'Product Deliverd')], default='pending', max_length=100)),
                ('amount', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='products.customerorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
