# Generated by Django 3.2 on 2022-11-14 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
