# Generated by Django 3.2 on 2022-11-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orderdetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='shipping_city',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Banglore', 'Banglore'), ('Delhi', 'Dehli'), ('AGRA', 'AGRA'), ('Surat', 'Surat'), ('Vadodra', 'Vadodra'), ('Bhopal', 'Bhopal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='shipping_state',
            field=models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Assam', 'Assam'), ('Chhattisgarh', 'Chhattisgarh'), ('Bihar', 'Bihar'), ('Rajasthan', 'Rajasthan'), ('Punjab', 'Punjab'), ('Karnataka', 'Karnataka'), ('Manipur', 'Manipur')], max_length=100),
        ),
    ]
