# Generated by Django 3.2 on 2022-11-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20221116_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='billing_city',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Banglore', 'Banglore'), ('Delhi', 'Dehli'), ('AGRA', 'AGRA'), ('Surat', 'Surat'), ('Vadodra', 'Vadodra'), ('Bhopal', 'Bhopal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='billing_state',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Banglore', 'Banglore'), ('Delhi', 'Dehli'), ('AGRA', 'AGRA'), ('Surat', 'Surat'), ('Vadodra', 'Vadodra'), ('Bhopal', 'Bhopal')], max_length=100),
        ),
    ]
