# Generated by Django 3.2 on 2022-11-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_customerorder_billing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order confirmed', 'Order confirmed'), ('Processing Order', 'Processing Order'), ('Quality Check', 'Quality Check'), ('Dispatched Item', 'Dispatched Item'), ('Product Delivered', 'Product Delivered')], default='pending', max_length=100),
        ),
    ]
